
title: Viplav Kumar Singh
email: viplavsingh1209@gmail.com
description: >-
  Senior DevOps Engineer | AWS | Terraform | CI/CD | Kubernetes | Platform Engineering
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://viplav12.github.io"
github_username: viplav12

theme: null

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  syntax_highlighter_opts:
    disable: true

include:
  - _pages
